[package]
name = "kvstore"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
fizzbee-mbt = "0.1.1"
tokio = { version = "1.48"}
object_store = "0.12"
serde_json = "1.0.145"
futures-util = "0.3.31"
mr-ulid = "2.0.0"
